qsub -l nodes=1:ppn=24,mem=30gb,walltime=148:60:00 dev/run_armet_on_cancer_type.sh -F Adrenocortical_Carcinoma_Primary_Tumor
qsub -l nodes=1:ppn=24,mem=30gb,walltime=148:60:00 dev/run_armet_on_cancer_type.sh -F Bladder_Urothelial_Carcinoma_Primary_Tumor
qsub -l nodes=1:ppn=24,mem=30gb,walltime=148:60:00 dev/run_armet_on_cancer_type.sh -F Brain_Lower_Grade_Glioma_Primary_Tumor
qsub -l nodes=1:ppn=24,mem=30gb,walltime=148:60:00 dev/run_armet_on_cancer_type.sh -F Breast_Invasive_Carcinoma_Primary_Tumor
qsub -l nodes=1:ppn=24,mem=30gb,walltime=148:60:00 dev/run_armet_on_cancer_type.sh -F Cervical_Squamous_Cell_Carcinoma_and_Endocervical_Adenocarcinoma_Primary_Tumor
qsub -l nodes=1:ppn=24,mem=30gb,walltime=148:60:00 dev/run_armet_on_cancer_type.sh -F Cholangiocarcinoma_Primary_Tumor
qsub -l nodes=1:ppn=24,mem=30gb,walltime=148:60:00 dev/run_armet_on_cancer_type.sh -F Colon_Adenocarcinoma_Primary_Tumor
qsub -l nodes=1:ppn=24,mem=30gb,walltime=148:60:00 dev/run_armet_on_cancer_type.sh -F Esophageal_Carcinoma_Primary_Tumor
qsub -l nodes=1:ppn=24,mem=30gb,walltime=148:60:00 dev/run_armet_on_cancer_type.sh -F Glioblastoma_Multiforme_Primary_Tumor
qsub -l nodes=1:ppn=24,mem=30gb,walltime=148:60:00 dev/run_armet_on_cancer_type.sh -F Head_and_Neck_Squamous_Cell_Carcinoma_Primary_Tumor
qsub -l nodes=1:ppn=24,mem=30gb,walltime=148:60:00 dev/run_armet_on_cancer_type.sh -F High-Risk_Wilms_Tumor_Primary_Tumor
qsub -l nodes=1:ppn=24,mem=30gb,walltime=148:60:00 dev/run_armet_on_cancer_type.sh -F Kidney_Chromophobe_Primary_Tumor
qsub -l nodes=1:ppn=24,mem=30gb,walltime=148:60:00 dev/run_armet_on_cancer_type.sh -F Kidney_Renal_Clear_Cell_Carcinoma_Primary_Tumor
qsub -l nodes=1:ppn=24,mem=30gb,walltime=148:60:00 dev/run_armet_on_cancer_type.sh -F Kidney_Renal_Papillary_Cell_Carcinoma_Primary_Tumor
qsub -l nodes=1:ppn=24,mem=30gb,walltime=148:60:00 dev/run_armet_on_cancer_type.sh -F Liver_Hepatocellular_Carcinoma_Primary_Tumor
qsub -l nodes=1:ppn=24,mem=30gb,walltime=148:60:00 dev/run_armet_on_cancer_type.sh -F Lung_Adenocarcinoma_Primary_Tumor
qsub -l nodes=1:ppn=24,mem=30gb,walltime=148:60:00 dev/run_armet_on_cancer_type.sh -F Lung_Squamous_Cell_Carcinoma_Primary_Tumor
qsub -l nodes=1:ppn=24,mem=30gb,walltime=148:60:00 dev/run_armet_on_cancer_type.sh -F Lymphoid_Neoplasm_Diffuse_Large_B-cell_Lymphoma_Primary_Tumor
qsub -l nodes=1:ppn=24,mem=30gb,walltime=148:60:00 dev/run_armet_on_cancer_type.sh -F Mesothelioma_Primary_Tumor
qsub -l nodes=1:ppn=24,mem=30gb,walltime=148:60:00 dev/run_armet_on_cancer_type.sh -F Neuroblastoma_Primary_Tumor
qsub -l nodes=1:ppn=24,mem=30gb,walltime=148:60:00 dev/run_armet_on_cancer_type.sh -F Ovarian_Serous_Cystadenocarcinoma_Primary_Tumor
qsub -l nodes=1:ppn=24,mem=30gb,walltime=148:60:00 dev/run_armet_on_cancer_type.sh -F Pancreatic_Adenocarcinoma_Primary_Tumor
qsub -l nodes=1:ppn=24,mem=30gb,walltime=148:60:00 dev/run_armet_on_cancer_type.sh -F Pheochromocytoma_and_Paraganglioma_Primary_Tumor
qsub -l nodes=1:ppn=24,mem=30gb,walltime=148:60:00 dev/run_armet_on_cancer_type.sh -F Prostate_Adenocarcinoma_Primary_Tumor
qsub -l nodes=1:ppn=24,mem=30gb,walltime=148:60:00 dev/run_armet_on_cancer_type.sh -F Rectum_Adenocarcinoma_Primary_Tumor
qsub -l nodes=1:ppn=24,mem=30gb,walltime=148:60:00 dev/run_armet_on_cancer_type.sh -F Sarcoma_Primary_Tumor
qsub -l nodes=1:ppn=24,mem=30gb,walltime=148:60:00 dev/run_armet_on_cancer_type.sh -F Skin_Cutaneous_Melanoma_Primary_Tumor
qsub -l nodes=1:ppn=24,mem=30gb,walltime=148:60:00 dev/run_armet_on_cancer_type.sh -F Stomach_Adenocarcinoma_Primary_Tumor
qsub -l nodes=1:ppn=24,mem=30gb,walltime=148:60:00 dev/run_armet_on_cancer_type.sh -F Testicular_Germ_Cell_Tumors_Primary_Tumor
qsub -l nodes=1:ppn=24,mem=30gb,walltime=148:60:00 dev/run_armet_on_cancer_type.sh -F Thymoma_Primary_Tumor
qsub -l nodes=1:ppn=24,mem=30gb,walltime=148:60:00 dev/run_armet_on_cancer_type.sh -F Thyroid_Carcinoma_Primary_Tumor
qsub -l nodes=1:ppn=24,mem=30gb,walltime=148:60:00 dev/run_armet_on_cancer_type.sh -F Uterine_Carcinosarcoma_Primary_Tumor
qsub -l nodes=1:ppn=24,mem=30gb,walltime=148:60:00 dev/run_armet_on_cancer_type.sh -F Uterine_Corpus_Endometrial_Carcinoma_Primary_Tumor
qsub -l nodes=1:ppn=24,mem=30gb,walltime=148:60:00 dev/run_armet_on_cancer_type.sh -F Uveal_Melanoma_Primary_Tumor
