---
title: "feature_selection"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#devtools::load_all()
library(tidyverse)
library(magrittr)
library(rstan)
library(foreach)
options(mc.cores = parallel::detectCores())
rstan_options(auto_write = TRUE)

my_theme = 	
	theme_bw() +
	theme(
		panel.border = element_blank(),
		axis.line = element_line(),
		panel.grid.major = element_line(size = 0.2),
		panel.grid.minor = element_line(size = 0.1),
		text = element_text(size=12),
		legend.position="bottom",
		aspect.ratio=1,
		axis.text.x = element_text(angle = 90, hjust = 1),
		strip.background = element_blank(),
		axis.title.x  = element_text(margin = margin(t = 10, r = 10, b = 10, l = 10)),
		axis.title.y  = element_text(margin = margin(t = 10, r = 10, b = 10, l = 10))
	)

nb_to_gamma = function(mu, phi){
	list(
		"shape" = (mu*phi)/(mu+phi), 
		"rate" = phi/(mu+phi)
	)
}

source("https://gist.githubusercontent.com/stemangiola/dd3573be22492fc03856cd2c53a755a9/raw/e4ec6a2348efc2f62b88f10b12e70f4c6273a10a/tidy_extensions.R")
source("https://gist.githubusercontent.com/stemangiola/90a528038b8c52b21f9cfa6bb186d583/raw/4ac3a7d74d4f7971bd8dd8eb470279eb7f42bbf8/transcription_tool_kit.R")
```


## R Markdown
```{r, cache=TRUE}

get_fit_df = function(fit_MPI, data_for_stan_MPI, counts_stan_MPI){

	fit_MPI %>%
	summary() %$% summary %>%
	as_tibble(rownames="par") %>%
	filter(grepl("lambda|sigma", par)) %>%
	separate(par, c("par", "G"), sep="\\[|\\]") %>%
	filter(par %in% c("lambda", "sigma_raw")) %>%
	select(par, G, "50%") %>% spread(par, "50%") %>%
	mutate(G = G %>% as.integer) %>%
	left_join(
		data_for_stan_MPI$symbols %>%
			gather(idx_MPI, symbol) %>%
			drop_na() %>% mutate(G=1:n())
	) %>%
	left_join( counts_stan_MPI %>% distinct(symbol, `Cell type category`)  ) %>%
	
	
	# Add stan normalisation constants
	left_join(counts) %>%
	left_join(
		fit_MPI %>%
			summary() %$% summary %>%
			as_tibble(rownames="par") %>%
			filter(grepl("exposure", par)) %>%
			separate(par, c("par", "S"), sep="\\[|\\]") %>%
			select(par, S, "50%") %>%
			rename(exposure = `50%`) %>%
			select(-par) %>%
			left_join(
				counts_stan_MPI %>% 
					distinct(sample, sample_idx) %>% 
					rename(S = sample_idx) %>% 
					mutate_if(is.integer, as.character)
			) 
	) %>%
	
	# Recalculate `read count normalised`
	mutate(`read count normalised bayes` = `read count` / exp(exposure))	%>%
		
		# QQ plots
	do_parallel_start(40, "symbol") %>%
	do({
	
		`%>%` = magrittr::`%>%`
		library(tidyverse)
		library(magrittr)
	
		(.) %>%
			group_by(symbol) %>%
			do(
				(.) %>%
					arrange(`read count normalised bayes`) %>%
					mutate(
						predicted_NB =
							qnbinom(
								ppoints(`read count normalised bayes`),
								size=.$sigma_raw %>% unique %>% exp %>% `^` (-1),
								mu=.$lambda %>% unique %>% exp
							)
					)
			) %>%
			ungroup()
	}) %>%
	do_parallel_end() %>%
	mutate(`log of error` = (`read count normalised bayes` - predicted_NB) %>% abs %>% `+` (1) %>% log) %>%
	mutate(`error of log` = (log(`read count normalised bayes` + 1) - log(predicted_NB + 1)) ) %>%
	mutate(`error scaled` =  ((`read count normalised bayes` - predicted_NB) / (`read count normalised bayes` + 1) )) %>%
	left_join(
		(.) %>%
			group_by(symbol) %>%
			summarise(`gene error mean` = `error of log` %>% abs %>% mean)
	) %>%
	
	mutate(
		symbol =
			gsub(
				(.) %>%
					distinct(`Cell type category`) %>%
					pull(1) %>%
					paste("_", sep="") %>%
					paste(collapse="|") ,
				"",
				symbol
			)
	) %>%
	
	# Convert to gamma	
	mutate(
		shape = nb_to_gamma(lambda %>% exp, 1/exp(sigma_raw)) %$% shape,
		rate = nb_to_gamma(lambda %>% exp, 1/exp(sigma_raw)) %$% rate
	) %>%
	
	# Calculate confidence interval	
	mutate(CI_low = qgamma(0.025, shape = shape, rate = rate)) %>%
	mutate(CI_high = qgamma(0.975, shape = shape, rate = rate)) 
}


level = 1
load(sprintf("/stornext/Home/data/allstaff/m/mangiola.s/PhD/deconvolution/ARMET/docs/fit_MPI_level1_23042019.RData", level))
load(sprintf("/stornext/Home/data/allstaff/m/mangiola.s/PhD/deconvolution/ARMET/docs/level_1_input_23042019.RData", level))

fit_df_1 = get_fit_df(fit_MPI, data_for_stan_MPI, counts_stan_MPI) %>% mutate(level = level)


level = 2
load(sprintf("/stornext/Home/data/allstaff/m/mangiola.s/PhD/deconvolution/ARMET/docs/fit_MPI_level2.RData", level))
load(sprintf("/stornext/Home/data/allstaff/m/mangiola.s/PhD/deconvolution/ARMET/docs/level_2_input.RData", level))

fit_df_2 = get_fit_df(fit_MPI, data_for_stan_MPI, counts_stan_MPI) %>% mutate(level = level)


fit_df_1 %>% mutate(level = 1) %>%
	bind_rows(fit_df_2 %>% mutate(level = 2)) %>%
	distinct(level, sample, symbol, `Cell type category`, `read count`, `read count normalised bayes`, `Data base`, lambda, sigma_raw) %>%
	
	# Replace the category house_keeping
	mutate(`house keeping` = `Cell type category` == "house_keeping") %>%
	rename(temp = `Cell type category`) %>%
	left_join( (.) %>% filter(temp != "house_keeping") %>% distinct(sample, temp, level) %>% rename(`Cell type category` = temp)) %>%
	select(-temp) %>%
	
	write_csv(sprintf("docs/ref.csv", level))


```

## Get global properties

```{r}
	fit_MPI %>%
	summary() %$% summary %>%
	as_tibble(rownames="par") %>%
	separate(par, c("par", "G"), sep="\\[|\\]") %>%
	filter(par %in% c( "sigma_intercept", "sigma_slope", "sigma_sigma", "lambda_sigma", "lambda_skew") ) %>%
	select(par, `50%`)

```


## See whether the normalisation worked

```{r}
fit_df %>% 
	distinct(`Cell type category`, symbol, lambda) %>% 
	ggplot(aes(lambda, color=`Cell type category`)) + 
	geom_density()

```


## Plot error rank

The threshold seems to be 0.5

```{r}

(
	fit_df %>%
	distinct(symbol, `Cell type category`, lambda, CI_low, CI_high, shape, rate, `gene error mean`) %>%
	inner_join(
		(.) %>%
		distinct(symbol, `Cell type category`) %>%
		count(symbol) %>%
		filter(n == fit_df %>% distinct(`Cell type category`) %>% nrow %>% `-` (1))
	) %>% 
 	unite(symbol_ct, c("symbol", "Cell type category"), remove=F) %>% 
 	sample_frac(0.01)  %>% 
 	arrange(`gene error mean` %>% desc) %>%
  mutate(symbol_ct = factor(symbol_ct, unique(symbol_ct))) %>%
  ggplot(aes(x = symbol_ct, y = `gene error mean` , color=`Cell type category`, size=lambda)) +
 	#geom_point(alpha=0.4)  + 
	geom_jitter(alpha=0.4, width = 25) +
 	theme(
 		axis.title.x=element_blank(),
	 axis.text.x=element_blank(),
	 axis.ticks.x=element_blank()
	) 
) %>% plotly::ggplotly()

fit_df %>% 
  filter(symbol %in% c("MFSD7")) %>%
	ggplot(aes(x=`predicted_NB` + 1, y=`read count normalised bayes` + 1, label=symbol, color=`Cell type category`)) + 
	geom_abline(intercept = 0, slope = 1, color="grey") + 
	geom_point() + 
	facet_wrap(~ symbol, scales = "free")  +
	expand_limits(y=1, x=1) + 
	scale_y_log10() +
	scale_x_log10() +
	my_theme 


```

## Select markers

```{r}

get_marker_df = function(fit_df, level, fit_threshold){

		fit_df %>% 
		left_join(level_df %>% mutate(`level 0` = "root")) %>%
		filter(`Cell type category` != "house_keeping") %>%
		inner_join( 
			(.) %>% 
				select(!!sprintf("level %s", level -1), !!sprintf("level %s", level)) %>% 
				distinct %>%
				group_by_at(1) %>% 
				summarise(n = n()) %>%
				filter(n > 1) 
		) %>%
		group_by(!!sym(sprintf("level %s", level -1))) %>%
		do(
				gtools::permutations(
					n=(.) %>% select(!!sprintf("level %s", level)) %>% distinct %>% drop_na %>% nrow,
					r=2,
					v=(.) %>% select(!!sprintf("level %s", level)) %>% distinct %>% drop_na %>% pull(1),
					repeats.allowed=F
				) %>%
				as_tibble
		) %>%
		mutate(comparison = 1:n()) %>%
		unite(pair, c("V1", "V2"), remove = F, sep=" ") %>%
		gather(which, `Cell type category`, -!!sprintf("level %s", level -1), -comparison, -pair) %>%
		left_join(
			fit_df %>% distinct(symbol, `Cell type category`, CI_low, CI_high)
		) %>% 
		mutate(relevant_CI = ifelse(which == "V1", CI_low, CI_high)) %>%
		group_by(comparison, pair, symbol) %>%
		arrange(which) %>%
		summarise(delta = diff(relevant_CI)) %>%
		separate(pair, c("Cell type category", "other Cell type category"), sep=" ", remove = F) %>%
		left_join( fit_df %>% distinct(`Cell type category`, symbol, lambda, `gene error mean`) ) %>%
		filter(lambda > 4) %>%
		filter(`gene error mean` < fit_threshold) %>%
		arrange(delta) %>%
		mutate(rank = 1:n()) %>%
		ungroup() %>% 
		mutate(level = !!level)
}

n_markers = 10

marker_df = 
	get_marker_df(fit_df_1, 1, 0.5) %>% 
	rbind(get_marker_df(fit_df_2, 2, 0.4))
	
marker_df %>%

# Filter markers
filter(rank < n_markers) %>%
	
# Filter markers in upper levels that have been selected for lower levels
inner_join(
	(.) %>% 
	distinct(symbol, level) %>%
	group_by(symbol) %>%
	arrange(level %>% desc) %>%
	slice(1) %>%
	ungroup
) %>%


# Write table
{
	(.)  %>%	write_csv("docs/markers.csv")
	(.)
} %>%


# Plot
select(-`Cell type category`, `other Cell type category`) %>%
left_join(
	rbind(fit_df_1, fit_df_2) %>% 
		distinct(`Cell type category`, symbol, sample, `read count normalised bayes`, level)
) %>%

mutate( symbol_err = sprintf("%s\n%s", symbol, `gene error mean` %>% round(2))) %>% 
{
	n_tot_markers = (.) %>% distinct(symbol) %>% nrow
	
	{ ggplot((.), aes(y=`read count normalised bayes` + 1, x=`Cell type category` %>% substring(1, 2), fill=`Cell type category`)) + 
		geom_boxplot() + 
		facet_wrap(~ pair + symbol_err, scale="free", ncol = 6 ) + 
		scale_y_log10() + 
		my_theme +
		theme(text = element_text(size = 6)	)
	} %>%
	ggsave(
		filename = sprintf('docs/markers_level_%s.pdf', level ), 
		height= 28 %>% divide_by(8) %>% multiply_by( n_tot_markers  ) %>% ceiling, 
		width= 21, 
		units = "cm", limitsize = FALSE
	)
}

```

OLD

```{r}
# Add proportion of markers based on cell differenc
left_join(
 (.)	%>% 
 	filter(delta_lambda>0) %>% 
 	group_by(`Cell type category query`, other_ct) %>% 
 	summarise(s = delta_lambda %>% sum) %>% 
 	ungroup() %>% 
 	mutate(p = 1/s) %>% 
 	mutate(p = p/max(p)) %>%
 	mutate(n_markers = (p * n_markers) %>% ceiling) %>%
 	select(-s, -p)
) %>%
	
# Select markers
group_by(`Cell type category query`, other_ct) %>%
filter(delta_lambda > 0) %>%
filter(rank < n_markers) %>%
ungroup() %>%
distinct(`Cell type category query`, symbol, `gene error mean`) 


marker_df %>%
# Write table
{
	(.) %>%	write_csv(sprintf("docs/markers_level%s.csv", level ))
	(.)
} %>%
	

# Plot


left_join(
fit_df %>% distinct(`Cell type category`, symbol, sample, `read count normalised bayes`)
) %>%
	

	
mutate( symbol_err = sprintf("%s %s", symbol,  `gene error mean` %>% round(2))) %>% 
{ ggplot((.), aes(y=`read count normalised bayes` + 1, x=`Cell type category` %>% substring(1, 2), fill=`Cell type category`)) + 
	geom_boxplot() + 
	facet_wrap(~ `Cell type category query` + symbol_err, scale="free", ncol = 6 ) + 
	scale_y_log10() + 
	my_theme +
	theme(text = element_text(size = 6)	)
} %>%
ggsave(
	filename = sprintf('docs/markers_level_%s.pdf', level ), 
	height= 28 %>% divide_by(8) %>% multiply_by( marker_df %>% distinct(symbol) %>% nrow %>% divide_by(6)) %>% ceiling, 
	width= 21, 
	units = "cm", limitsize = FALSE
)


	


	
```

```{r, cache=TRUE}









```

