// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;


RcppExport SEXP _rcpp_module_boot_stan_fit4ARMET_ref_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4ARMET_tc_fix_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4ARMET_tc_fix_hierarchical_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4proof_concept_mod();

static const R_CallMethodDef CallEntries[] = {
    {"_rcpp_module_boot_stan_fit4ARMET_ref_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4ARMET_ref_mod, 0},
    {"_rcpp_module_boot_stan_fit4ARMET_tc_fix_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4ARMET_tc_fix_mod, 0},
    {"_rcpp_module_boot_stan_fit4ARMET_tc_fix_hierarchical_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4ARMET_tc_fix_hierarchical_mod, 0},
    {"_rcpp_module_boot_stan_fit4proof_concept_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4proof_concept_mod, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_ARMET(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
